name: Cronjob fo filestore backup

on:   
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Sleep for 300 seconds
      uses: LnkAsia/wait-action-@master
      with:
        time: '30s'
